---
# SOMEHOW THE SETTINGS DONT CHANGE
- name: Configure macOS preferences
  shell: |
    # Enable auto-hide for the Dock
    defaults write com.apple.dock autohide -bool true
    
    # Set Dock position to the left
    defaults write com.apple.dock orientation -string "left"
    
    # Hide all items on the Desktop
    defaults write com.apple.finder CreateDesktop -bool false
    
    # Disable natural scrolling
    defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false
    
    # Set Dark Mode
    defaults write NSGlobalDomain AppleInterfaceStyle -string "Dark"
    
    # Show Bluetooth in menu bar
    defaults write com.apple.controlcenter "NSStatusItem Visible Bluetooth" -bool true
    
    # Show Battery percentage in menu bar
    defaults write com.apple.menuextra.battery ShowPercent -bool true
    
    # Show Sound in menu bar
    defaults write com.apple.controlcenter "NSStatusItem Visible Sound" -bool true

    # Turn off widgets on the desktop
    defaults write com.apple.dashboard mcx-disabled -bool true
    killall Dock

    # Turn off widgets in Stage Manager (if available in your macOS version)
    defaults write com.apple.stage-manager showWidgets -bool false
    killall Dock
    killall Finder
